In [1]:
import pandas as pd
import numpy as np

In [2]:
class linear():
    def __init__(self):
        self.lr=0.02
        self.itr=100
        
    def fit(self,x,y):
        self.m,self.n=x.shape
        self.w=np.zeros(self.n)
        self.b=0
        self.x=x
        self.y=y
        
        for i in range(self.itr):
            self.update_w()
    
    def update_w(self):
        
        y_p=self.predict(self.x)
        
        dw=np.dot(self.x.T,y_p - y)
        dw*=2
        dw=dw/self.m
        
        db=np.sum(y_p - y)
        db*=2
        db=db/self.m
        
        self.w=self.w - self.lr*dw
        self.b=self.b - self.lr*db

    def predict(self,x):
        return np.dot(x,self.w)+self.b

In [3]:
df = pd.read_csv('~/system/vs/jupyter/dataset/Salary_dataset.csv')
df=df.drop('Unnamed: 0',axis=1)
df.shape

(30, 2)

In [4]:
x=df[['YearsExperience']].values
y=df['Salary'].values
x.shape,y.shape,x,y

((30, 1),
 (30,),
 array([[ 1.2],
        [ 1.4],
        [ 1.6],
        [ 2.1],
        [ 2.3],
        [ 3. ],
        [ 3.1],
        [ 3.3],
        [ 3.3],
        [ 3.8],
        [ 4. ],
        [ 4.1],
        [ 4.1],
        [ 4.2],
        [ 4.6],
        [ 5. ],
        [ 5.2],
        [ 5.4],
        [ 6. ],
        [ 6.1],
        [ 6.9],
        [ 7.2],
        [ 8. ],
        [ 8.3],
        [ 8.8],
        [ 9.1],
        [ 9.6],
        [ 9.7],
        [10.4],
        [10.6]]),
 array([ 39344.,  46206.,  37732.,  43526.,  39892.,  56643.,  60151.,
         54446.,  64446.,  57190.,  63219.,  55795.,  56958.,  57082.,
         61112.,  67939.,  66030.,  83089.,  81364.,  93941.,  91739.,
         98274., 101303., 113813., 109432., 105583., 116970., 112636.,
        122392., 121873.]))

In [5]:
y=y/y.mean()

In [12]:
dw=np.dot(x.T,y_pred - y)
dw

array([0.11977218])

In [6]:
model=linear()
model.fit(x,y)

In [7]:
y_pred=model.predict(x)
y_pred

array([0.36707724, 0.39582979, 0.42458234, 0.49646373, 0.52521628,
       0.62585021, 0.64022649, 0.66897904, 0.66897904, 0.74086042,
       0.76961297, 0.78398925, 0.78398925, 0.79836553, 0.85587063,
       0.91337574, 0.94212829, 0.97088084, 1.0571385 , 1.07151477,
       1.18652498, 1.22965381, 1.34466402, 1.38779285, 1.45967423,
       1.50280306, 1.57468444, 1.58906072, 1.68969465, 1.71844721])

In [8]:
from sklearn.metrics import mean_squared_error,r2_score

/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [9]:
mean_squared_error(y,y_pred),r2_score(y,y_pred)
#r2 score tells if the model fits the properly or not. if r2 score is high it means that 
#the model fits the data well, and if low it does not fit data well. r2_score if good above 0.7 
#or 0.8

#mean_squared_error give the mean of all the error values.

(0.009091735725549693, 0.9277089513535643)